server:
  url: "${SERVER_URL:http://localhost}"
  port: 5000
  servlet:
    context-path: /api/repaint-game

frontend:
  url: "${FRONTEND_URL:http://localhost:3000}"

python:
  game-path: python/game.py

keycloak:
  port : 8282
  url: "${KEYCLOAK_URL:${server.url}:${keycloak.port}}"
  realm: "repaintinggame"
  jwt:
    auth:
      converter:
        principle-attribute: preferred_username
        resource-id: repaint-game

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.url}/realms/${keycloak.realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  datasource:
    driver-class-name: org.postgresql.Driver
    url: "${POSTGRESQL_REPAINT_GAME_URI:jdbc:postgresql://localhost:5436/repaint_game_db?stringtype=unspecified}"
    username: "${POSTGRESQL_REPAINT_GAME_USER:dnlkk}"
    password: "${POSTGRESQL_REPAINT_GAME_PASS:dnlkkpass}"
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

logging:
  level:
    com:
      example:
        therepaintinggameweb:
          - DEBUG
          - INFO
  file:
    name: logs/repaint.log
