server:
  url: "http://localhost"
  port: 5000
  servlet:
    context-path: /api

frontend:
  url: "http://localhost:3000"

python:
  game-path: python/game.py

keycloak:
  port : 8282
  url: "${server.url}:${keycloak.port}"
  realm: "repaintinggame"

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak.url}/realms/${keycloak.realm}/protocol/openid-connect/certs
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/danilkk_db
#    username: danilkk
#    password: 123
#  jpa:
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

